### ISSUE TITLE
Unhandled Exception: A VideoPlayerController was used after being disposed.

### ISSUE THREAD

**Issue by MartinLangbecker** [MartinLangbecker/wokubot#30]
When creating a new media entry (media list --> "+") and tapping on the "+" to select a media file, the following error occurs:

```
E/flutter ( 5267): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: A VideoPlayerController was used after being disposed.
E/flutter ( 5267): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
E/flutter ( 5267): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:117
E/flutter ( 5267): #1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:123
E/flutter ( 5267): #2      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:217
E/flutter ( 5267): #3      ValueNotifier.value=
package:flutter/…/foundation/change_notifier.dart:292
E/flutter ( 5267): #4      VideoPlayerController.pause
package:video_player/video_player.dart:377
E/flutter ( 5267): #5      _VideoAppLifeCycleObserver.didChangeAppLifecycleState
package:video_player/video_player.dart:556
E/flutter ( 5267): #6      WidgetsBinding.handleAppLifecycleStateChanged
package:flutter/…/widgets/binding.dart:704
E/flutter ( 5267): #7      ServicesBinding._handleLifecycleMessage
package:flutter/…/services/binding.dart:192
E/flutter ( 5267): #8      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:74
E/flutter ( 5267): #9      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:283
E/flutter ( 5267): #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter ( 5267): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5267): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5267): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5267): #14     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter ( 5267): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
´´´

**Comment by MartinLangbecker** [comment]
This may help: https://stackoverflow.com/questions/58955831/flutter-video-player-dispose

**Comment by MartinLangbecker** [comment]
Switched video player to Chewie in commit https://github.com/MartinLangbecker/wokubot/commit/7a93e320b09f05210061634a8a0cb329bb7e086d, rendering this problem obsolete.
